version: "3.7"

volumes:
  postgres-data:
  etcd_data:
    driver: ${ENV_VOLUME_DRIVER}

networks:
  xendit:
    name: xendit_network

services:
  node_xendit:
    build:
      context: ./
    command: ["yarn", "dev"]
    volumes:
      - ./src:/www/src:delegated
      - ./tests:/www/tests:delegated
      - ./migrations:/www/migrations:delegated
    depends_on:
      - postgres
    networks:
      xendit:
        aliases:
          - node_xendit
    environment:
      - ENV

  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3800:80
    networks:
      xendit:
        aliases:
          - node_xendit
    depends_on:
      - node_xendit

  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PORT=${DATABASE_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      xendit:
        aliases:
          - xendit_postgres